language: ruby

rvm:
  - 2.3.3

before_script:
 - chmod +x ./cibuild

script: ./cibuild

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: _site
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
